name: Patrick Darling
favicon: null
layout_spectrum: 0.4577239998616278
typography_spectrum: 0.9672986967489123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3292717228177935
  lightness: 0.009628049796447158
  saturation: 0.7508518910035491
  rhythmicContrast: 0.08798836544156075
purpose: []
