name: Patrick Darling
favicon: null
layout_spectrum: 0.4577239998616278
typography_spectrum: 0.9672986967489123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#546776'
    - '#130502'
    - '#783602'
    - '#e0964f'
    - '#fede9c'
  brandStrength: 0.0625
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
