name: Patrick Darling
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.7459
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#546776'
    - '#130502'
    - '#783602'
    - '#e0964f'
    - '#fede9c'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
